#!/bin/bash

NOTES_DIR="/home/core/Temp/MEGA/Notes"
EDITOR=nvim
VIEW=zathura
TERMINAL=kitty

# ------------------------ #
create_document() {
  # Use rofi to prompt the user to select the type of document to create
  document_type=$(echo -e "Basic\nLaTeX\nBeamer\nRmark" | rofi -dmenu -p "What kind of note?")

  # Check if the user cancelled the prompt
  if [ -z "$document_type" ]; then
    return
  fi

  case "$document_type" in
    Basic)
      template="SimpleNote.md"
      EXTENSION="md"
      message="Basic Document Created!"
      ;;
    LaTeX)
      template="LaTeX.tex"
      EXTENSION="tex"
      message="LaTeX Document Created!"
      ;;
    Beamer)
      template="Presentation.tex"
      EXTENSION="tex"
      message="Beamer Presentation Created!"
      ;;
    Rmark)
      template="RMarkdown.rmd"
      EXTENSION="rmd"
      message="R Markdown Document Created!"
      ;;
    *)
      echo "Invalid option"
      return 1
      ;;
  esac

  # Use rofi to prompt the user to enter a name for the note
  cn_name=$(rofi -dmenu -p "Enter a name for the note:")

  # Check if the user cancelled the prompt
  if [ -z "$cn_name" ]; then
    return
  fi

  # Check if the file already exists
  if [ -f "$NOTES_DIR/$cn_name.$EXTENSION" ]; then
    # Prompt the user to confirm if they want to overwrite the file
    if ! (echo -e "Yes\nNo" | rofi -dmenu -p "Note already exists. Overwrite?" | grep -q "Yes"); then
      return
    fi
  fi

  notify-send "$message"
  cp "$NOTES_DIR/Templates/$template" "$NOTES_DIR/$cn_name.$EXTENSION"
  "$TERMINAL" -e "$EDITOR" "$NOTES_DIR/$cn_name.$EXTENSION"
}

open_document() {
  documuent=$(find "$directory" -type f \( -iname "*.*" \))
  selected_document=$(echo "$documuent" | rofi -dmenu -p "📖 Open:")
  if [[ -n $selected_document ]]; then
    $VIEW "$selected_document"
  fi
}

edit_notes() {
  documuent=$(find "$directory" -type f \( -iname "*.*" \))
  selected_document=$(echo "$documuent" | rofi -dmenu -p "📖 Open:")
  if [[ -n $selected_document ]]; then
    $TERMINAL -e $EDITOR "$selected_document"
  fi
}

main() {
  # Prompt the user to select "Library" or "Articles" using Rofi
  selected_dir=$(echo -e "📑 Create Note\n🔖 View Notes\n📚 Library\n📜 Articles" | rofi -dmenu -p "📂 Choose an action:")
  # Set the directory based on the user's selection
  # if selected_dir is not empty
  if [[ -n $selected_dir ]]; then
      case $selected_dir in
          "📑 Create Note")
              create_document
              ;;
          "🔖 View Notes")
              directory="/home/core/Temp/MEGA/Notes"
              edit_notes
              ;;
          "📚 Library")
              directory="/home/core/Documents/Books"
              open_document
              ;;
          "📜 Articles")
              directory="/home/core/Temp/MEGA/Zotero"
              open_document
              ;;
      esac
  else
    exit 0
  fi
}

main
