#!/bin/bash

TERMINAL=$(basename "$SHELL")
VIEW="<your_fav_viewer>"
EDITOR=vim
THEME=""
#e.g., rounded-purple-dark

# <<------ Directories ------>> #
book_library="<path_to_your_book_library>"
template_library="<path_to_your_templates>"
note_library="<path_to_your_note_library>"
article_library="<path_to_your_article_library>"

# <<------ Options ------>> #
declare -A actions
actions["📑 Create Note"]=$template_library
actions["🔖 View Notes"]=$note_library
actions["📚 Books"]=$book_library
actions["📜 Articles"]=$article_library
actions["⏬ Download Books"]="download_books"

# <<------ Main ------>> #
create_document() {
  document_type=$(echo -e "Basic\nLaTeX\nBeamer\nRmark" | rofi -dmenu -i -p "What kind of note?" ${THEME:+-theme $THEME})

  if [ -z "$document_type" ]; then
    return
  fi

  case "$document_type" in
    Basic)
      template="SimpleNote.md"
      EXTENSION="md"
      message="Basic Document Created!"
      ;;
    LaTeX)
      template="LaTeX.tex"
      EXTENSION="tex"
      message="LaTeX Document Created!"
      ;;
    Beamer)
      template="Presentation.tex"
      EXTENSION="tex"
      message="Beamer Presentation Created!"
      ;;
    Rmark)
      template="RMarkdown.rmd"
      EXTENSION="rmd"
      message="R Markdown Document Created!"
      ;;
    *)
      echo "Invalid option"
      return 1
      ;;
  esac

  cn_name=$(rofi -dmenu -p "Enter a name for the note:" ${THEME:+-theme $THEME})

  if [ -z "$cn_name" ]; then
    return
  fi

  if [ -f "$directory/$cn_name.$EXTENSION" ]; then
    if ! (echo -e "Yes\nNo" | rofi -dmenu -p "Note already exists. Overwrite?" ${THEME:+-theme $THEME} | grep -q "Yes"); then
      return
    fi
  fi

  notify-send "$message"
  cp "$directory/Templates/$template" "$directory/$cn_name.$EXTENSION"
  "$TERMINAL" -e "$EDITOR" "$directory/$cn_name.$EXTENSION"
}

open_document() {
  document=$(rg --files --iglob "*.pdf" --iglob "*.epub" --iglob "*.mobi" $directory)
  selected_document=$(echo "$document" | rofi -dmenu -i -p "📖 Open:" ${THEME:+-theme $THEME})
  if [[ -n $selected_document ]]; then
    $VIEW "$selected_document"
  fi
}

edit_notes() {
  document=$(rg --files --iglob "*.md" --iglob "*.wiki" --iglob "*.tex" $directory)
  selected_document=$(echo "$document" | rofi -dmenu -i -p "📖 Open:" ${THEME:+-theme $THEME})
  if [[ -n $selected_document ]]; then
    $TERMINAL -e $EDITOR "$selected_document"
  fi
}

download_books() {
  bookname=$(echo "" | rofi -dmenu -p "Enter book name:" ${THEME:+-theme $THEME})
  if [ -z "$bookname" ]
  then
      echo "No book name entered"
      exit 1
  fi

  kitty -T "dropbooks" -e libby --rofi $bookname
}

main() {
  selected_action=$(printf '%s\n' "${!actions[@]}" | rofi -dmenu -i -p "📂 Choose an action:" ${THEME:+-theme $THEME})
  
  if [ -z "$selected_action" ]; then
    exit 0
  fi

  selected_dir_or_func="${actions[$selected_action]}"

  if [ "$selected_dir_or_func" = "download_books" ]; then
    $selected_dir_or_func
  else
    directory="$selected_dir_or_func"
    case $selected_action in
      "📑 Create Note")
        create_document
        ;;
      "🔖 View Notes")
        edit_notes
        ;;
      "📚 Books" | "📜 Articles")
        open_document
        ;;
    esac
  fi
}

main
